; ============================================================
;  USB2MIDI — PlatformIO + earlphilhower Arduino-Pico
;  Board : Waveshare RP2350-USB-A
; ============================================================

[platformio]
default_envs = usb2midi

[env:usb2midi]
platform  = https://github.com/maxgerhardt/platform-raspberrypi.git
board     = rpipico2
framework = arduino

board_build.core  = earlephilhower
board_build.f_cpu = 120000000L

board_build.arduino.earlephilhower.usb_stack = tinyusb
board_build.filesystem_size                  = 0.5m

build_flags =
    -D USE_TINYUSB
    -D PIN_USB_HOST_DP=12
    -I lib/pio_usb

lib_deps =
    adafruit/Adafruit TinyUSB Library @ 3.4.4
    bblanchon/ArduinoJson @ ^7.0.0
    fortyseveneffects/MIDI Library @ ^5.0.2

lib_extra_dirs = lib

monitor_speed   = 115200
monitor_filters = direct